language: php

services: mysql

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - mysql -e 'CREATE DATABASE class8;'

# script: vendor/bin/phpunit --verbose
script: phpunit --coverage-text --configuration phpunit.xml